[SERVICE]
    flush  1
    parsers_file parsers.conf
    parsers_file /fluent-bit/etc/parsers_custom.conf
    log_level warning

[INPUT]
    name tail
    path /var/lib/docker/containers/*/*.log
    db /fluent-bit/etc/flb_docker.db
    mem_buf_limit 5mb
    skip_long_lines On
    parser docker

[FILTER]
    name    grep
    match   *
    # Exclude Go health checks
    exclude log /health
    # Exclude Next.js static assets
    exclude log \.css|\.js|\.png|\.ico|\_next
    # Exclude Traefik metrics
    exclude log /metrics

[FILTER]
    Name parser
    Match *
    Key_Name log
    Parser golang_json
    Reserve_Data On
    Preserve_Key On

[OUTPUT]
    name    http
    match   *
    tls     On
    host    ${LOG_BETTERSTACK_HOST}
    port    443
    uri     /fluentbit
    header  Authorization Bearer ${LOG_BETTERSTACK_TOKEN}
    header  Content-Type application/json
    format  json
    retry_limit 5