// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: proto/quartz.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartRegistrationRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RegistrationRequest string                 `protobuf:"bytes,1,opt,name=registrationRequest,proto3" json:"registrationRequest,omitempty"`
	Email               string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StartRegistrationRequest) Reset() {
	*x = StartRegistrationRequest{}
	mi := &file_proto_quartz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRegistrationRequest) ProtoMessage() {}

func (x *StartRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quartz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRegistrationRequest.ProtoReflect.Descriptor instead.
func (*StartRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_proto_quartz_proto_rawDescGZIP(), []int{0}
}

func (x *StartRegistrationRequest) GetRegistrationRequest() string {
	if x != nil {
		return x.RegistrationRequest
	}
	return ""
}

func (x *StartRegistrationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type StartRegistrationResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Nonce                string                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	RegistrationResponse string                 `protobuf:"bytes,2,opt,name=registrationResponse,proto3" json:"registrationResponse,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *StartRegistrationResponse) Reset() {
	*x = StartRegistrationResponse{}
	mi := &file_proto_quartz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRegistrationResponse) ProtoMessage() {}

func (x *StartRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quartz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRegistrationResponse.ProtoReflect.Descriptor instead.
func (*StartRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_proto_quartz_proto_rawDescGZIP(), []int{1}
}

func (x *StartRegistrationResponse) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *StartRegistrationResponse) GetRegistrationResponse() string {
	if x != nil {
		return x.RegistrationResponse
	}
	return ""
}

type FinishRegistrationRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RegistrationRecord string                 `protobuf:"bytes,1,opt,name=registrationRecord,proto3" json:"registrationRecord,omitempty"`
	Nonce              string                 `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FinishRegistrationRequest) Reset() {
	*x = FinishRegistrationRequest{}
	mi := &file_proto_quartz_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishRegistrationRequest) ProtoMessage() {}

func (x *FinishRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quartz_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishRegistrationRequest.ProtoReflect.Descriptor instead.
func (*FinishRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_proto_quartz_proto_rawDescGZIP(), []int{2}
}

func (x *FinishRegistrationRequest) GetRegistrationRecord() string {
	if x != nil {
		return x.RegistrationRecord
	}
	return ""
}

func (x *FinishRegistrationRequest) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

type FinishRegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishRegistrationResponse) Reset() {
	*x = FinishRegistrationResponse{}
	mi := &file_proto_quartz_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishRegistrationResponse) ProtoMessage() {}

func (x *FinishRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quartz_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishRegistrationResponse.ProtoReflect.Descriptor instead.
func (*FinishRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_proto_quartz_proto_rawDescGZIP(), []int{3}
}

func (x *FinishRegistrationResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *FinishRegistrationResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type StartLoginRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Email              string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	UserIdentifier     string                 `protobuf:"bytes,2,opt,name=userIdentifier,proto3" json:"userIdentifier,omitempty"`
	StartLoginRequest  string                 `protobuf:"bytes,3,opt,name=startLoginRequest,proto3" json:"startLoginRequest,omitempty"`
	RegistrationRecord string                 `protobuf:"bytes,4,opt,name=registrationRecord,proto3" json:"registrationRecord,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StartLoginRequest) Reset() {
	*x = StartLoginRequest{}
	mi := &file_proto_quartz_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartLoginRequest) ProtoMessage() {}

func (x *StartLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quartz_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartLoginRequest.ProtoReflect.Descriptor instead.
func (*StartLoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_quartz_proto_rawDescGZIP(), []int{4}
}

func (x *StartLoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *StartLoginRequest) GetUserIdentifier() string {
	if x != nil {
		return x.UserIdentifier
	}
	return ""
}

func (x *StartLoginRequest) GetStartLoginRequest() string {
	if x != nil {
		return x.StartLoginRequest
	}
	return ""
}

func (x *StartLoginRequest) GetRegistrationRecord() string {
	if x != nil {
		return x.RegistrationRecord
	}
	return ""
}

type StartLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         string                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	LoginResponse string                 `protobuf:"bytes,2,opt,name=loginResponse,proto3" json:"loginResponse,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartLoginResponse) Reset() {
	*x = StartLoginResponse{}
	mi := &file_proto_quartz_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartLoginResponse) ProtoMessage() {}

func (x *StartLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quartz_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartLoginResponse.ProtoReflect.Descriptor instead.
func (*StartLoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_quartz_proto_rawDescGZIP(), []int{5}
}

func (x *StartLoginResponse) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *StartLoginResponse) GetLoginResponse() string {
	if x != nil {
		return x.LoginResponse
	}
	return ""
}

type FinishLoginRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Nonce              string                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	FinishLoginRequest string                 `protobuf:"bytes,2,opt,name=finishLoginRequest,proto3" json:"finishLoginRequest,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FinishLoginRequest) Reset() {
	*x = FinishLoginRequest{}
	mi := &file_proto_quartz_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishLoginRequest) ProtoMessage() {}

func (x *FinishLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quartz_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishLoginRequest.ProtoReflect.Descriptor instead.
func (*FinishLoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_quartz_proto_rawDescGZIP(), []int{6}
}

func (x *FinishLoginRequest) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *FinishLoginRequest) GetFinishLoginRequest() string {
	if x != nil {
		return x.FinishLoginRequest
	}
	return ""
}

type FinishLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionKey    string                 `protobuf:"bytes,1,opt,name=sessionKey,proto3" json:"sessionKey,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishLoginResponse) Reset() {
	*x = FinishLoginResponse{}
	mi := &file_proto_quartz_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishLoginResponse) ProtoMessage() {}

func (x *FinishLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quartz_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishLoginResponse.ProtoReflect.Descriptor instead.
func (*FinishLoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_quartz_proto_rawDescGZIP(), []int{7}
}

func (x *FinishLoginResponse) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

func (x *FinishLoginResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

var File_proto_quartz_proto protoreflect.FileDescriptor

const file_proto_quartz_proto_rawDesc = "" +
	"\n" +
	"\x12proto/quartz.proto\x12\rquartzservice\"b\n" +
	"\x18StartRegistrationRequest\x120\n" +
	"\x13registrationRequest\x18\x01 \x01(\tR\x13registrationRequest\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"e\n" +
	"\x19StartRegistrationResponse\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\tR\x05nonce\x122\n" +
	"\x14registrationResponse\x18\x02 \x01(\tR\x14registrationResponse\"a\n" +
	"\x19FinishRegistrationRequest\x12.\n" +
	"\x12registrationRecord\x18\x01 \x01(\tR\x12registrationRecord\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\tR\x05nonce\"H\n" +
	"\x1aFinishRegistrationResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\"\xaf\x01\n" +
	"\x11StartLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12&\n" +
	"\x0euserIdentifier\x18\x02 \x01(\tR\x0euserIdentifier\x12,\n" +
	"\x11startLoginRequest\x18\x03 \x01(\tR\x11startLoginRequest\x12.\n" +
	"\x12registrationRecord\x18\x04 \x01(\tR\x12registrationRecord\"P\n" +
	"\x12StartLoginResponse\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\tR\x05nonce\x12$\n" +
	"\rloginResponse\x18\x02 \x01(\tR\rloginResponse\"Z\n" +
	"\x12FinishLoginRequest\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\tR\x05nonce\x12.\n" +
	"\x12finishLoginRequest\x18\x02 \x01(\tR\x12finishLoginRequest\"K\n" +
	"\x13FinishLoginResponse\x12\x1e\n" +
	"\n" +
	"sessionKey\x18\x01 \x01(\tR\n" +
	"sessionKey\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email2\x99\x03\n" +
	"\x1bQuartzInternalCryptoService\x12f\n" +
	"\x11StartRegistration\x12'.quartzservice.StartRegistrationRequest\x1a(.quartzservice.StartRegistrationResponse\x12i\n" +
	"\x12FinishRegistration\x12(.quartzservice.FinishRegistrationRequest\x1a).quartzservice.FinishRegistrationResponse\x12Q\n" +
	"\n" +
	"StartLogin\x12 .quartzservice.StartLoginRequest\x1a!.quartzservice.StartLoginResponse\x12T\n" +
	"\vFinishLogin\x12!.quartzservice.FinishLoginRequest\x1a\".quartzservice.FinishLoginResponseB\x0eZ\fquartz/protob\x06proto3"

var (
	file_proto_quartz_proto_rawDescOnce sync.Once
	file_proto_quartz_proto_rawDescData []byte
)

func file_proto_quartz_proto_rawDescGZIP() []byte {
	file_proto_quartz_proto_rawDescOnce.Do(func() {
		file_proto_quartz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_quartz_proto_rawDesc), len(file_proto_quartz_proto_rawDesc)))
	})
	return file_proto_quartz_proto_rawDescData
}

var file_proto_quartz_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_quartz_proto_goTypes = []any{
	(*StartRegistrationRequest)(nil),   // 0: quartzservice.StartRegistrationRequest
	(*StartRegistrationResponse)(nil),  // 1: quartzservice.StartRegistrationResponse
	(*FinishRegistrationRequest)(nil),  // 2: quartzservice.FinishRegistrationRequest
	(*FinishRegistrationResponse)(nil), // 3: quartzservice.FinishRegistrationResponse
	(*StartLoginRequest)(nil),          // 4: quartzservice.StartLoginRequest
	(*StartLoginResponse)(nil),         // 5: quartzservice.StartLoginResponse
	(*FinishLoginRequest)(nil),         // 6: quartzservice.FinishLoginRequest
	(*FinishLoginResponse)(nil),        // 7: quartzservice.FinishLoginResponse
}
var file_proto_quartz_proto_depIdxs = []int32{
	0, // 0: quartzservice.QuartzInternalCryptoService.StartRegistration:input_type -> quartzservice.StartRegistrationRequest
	2, // 1: quartzservice.QuartzInternalCryptoService.FinishRegistration:input_type -> quartzservice.FinishRegistrationRequest
	4, // 2: quartzservice.QuartzInternalCryptoService.StartLogin:input_type -> quartzservice.StartLoginRequest
	6, // 3: quartzservice.QuartzInternalCryptoService.FinishLogin:input_type -> quartzservice.FinishLoginRequest
	1, // 4: quartzservice.QuartzInternalCryptoService.StartRegistration:output_type -> quartzservice.StartRegistrationResponse
	3, // 5: quartzservice.QuartzInternalCryptoService.FinishRegistration:output_type -> quartzservice.FinishRegistrationResponse
	5, // 6: quartzservice.QuartzInternalCryptoService.StartLogin:output_type -> quartzservice.StartLoginResponse
	7, // 7: quartzservice.QuartzInternalCryptoService.FinishLogin:output_type -> quartzservice.FinishLoginResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_quartz_proto_init() }
func file_proto_quartz_proto_init() {
	if File_proto_quartz_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_quartz_proto_rawDesc), len(file_proto_quartz_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_quartz_proto_goTypes,
		DependencyIndexes: file_proto_quartz_proto_depIdxs,
		MessageInfos:      file_proto_quartz_proto_msgTypes,
	}.Build()
	File_proto_quartz_proto = out.File
	file_proto_quartz_proto_goTypes = nil
	file_proto_quartz_proto_depIdxs = nil
}
