// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/quartz.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QuartzInternalCryptoService_StartRegistration_FullMethodName  = "/quartzservice.QuartzInternalCryptoService/StartRegistration"
	QuartzInternalCryptoService_FinishRegistration_FullMethodName = "/quartzservice.QuartzInternalCryptoService/FinishRegistration"
	QuartzInternalCryptoService_StartLogin_FullMethodName         = "/quartzservice.QuartzInternalCryptoService/StartLogin"
	QuartzInternalCryptoService_FinishLogin_FullMethodName        = "/quartzservice.QuartzInternalCryptoService/FinishLogin"
)

// QuartzInternalCryptoServiceClient is the client API for QuartzInternalCryptoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QuartzInternalCryptoServiceClient interface {
	StartRegistration(ctx context.Context, in *StartRegistrationRequest, opts ...grpc.CallOption) (*StartRegistrationResponse, error)
	FinishRegistration(ctx context.Context, in *FinishRegistrationRequest, opts ...grpc.CallOption) (*FinishRegistrationResponse, error)
	StartLogin(ctx context.Context, in *StartLoginRequest, opts ...grpc.CallOption) (*StartLoginResponse, error)
	FinishLogin(ctx context.Context, in *FinishLoginRequest, opts ...grpc.CallOption) (*FinishLoginResponse, error)
}

type quartzInternalCryptoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQuartzInternalCryptoServiceClient(cc grpc.ClientConnInterface) QuartzInternalCryptoServiceClient {
	return &quartzInternalCryptoServiceClient{cc}
}

func (c *quartzInternalCryptoServiceClient) StartRegistration(ctx context.Context, in *StartRegistrationRequest, opts ...grpc.CallOption) (*StartRegistrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartRegistrationResponse)
	err := c.cc.Invoke(ctx, QuartzInternalCryptoService_StartRegistration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quartzInternalCryptoServiceClient) FinishRegistration(ctx context.Context, in *FinishRegistrationRequest, opts ...grpc.CallOption) (*FinishRegistrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinishRegistrationResponse)
	err := c.cc.Invoke(ctx, QuartzInternalCryptoService_FinishRegistration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quartzInternalCryptoServiceClient) StartLogin(ctx context.Context, in *StartLoginRequest, opts ...grpc.CallOption) (*StartLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartLoginResponse)
	err := c.cc.Invoke(ctx, QuartzInternalCryptoService_StartLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quartzInternalCryptoServiceClient) FinishLogin(ctx context.Context, in *FinishLoginRequest, opts ...grpc.CallOption) (*FinishLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinishLoginResponse)
	err := c.cc.Invoke(ctx, QuartzInternalCryptoService_FinishLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuartzInternalCryptoServiceServer is the server API for QuartzInternalCryptoService service.
// All implementations must embed UnimplementedQuartzInternalCryptoServiceServer
// for forward compatibility.
type QuartzInternalCryptoServiceServer interface {
	StartRegistration(context.Context, *StartRegistrationRequest) (*StartRegistrationResponse, error)
	FinishRegistration(context.Context, *FinishRegistrationRequest) (*FinishRegistrationResponse, error)
	StartLogin(context.Context, *StartLoginRequest) (*StartLoginResponse, error)
	FinishLogin(context.Context, *FinishLoginRequest) (*FinishLoginResponse, error)
	mustEmbedUnimplementedQuartzInternalCryptoServiceServer()
}

// UnimplementedQuartzInternalCryptoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQuartzInternalCryptoServiceServer struct{}

func (UnimplementedQuartzInternalCryptoServiceServer) StartRegistration(context.Context, *StartRegistrationRequest) (*StartRegistrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartRegistration not implemented")
}
func (UnimplementedQuartzInternalCryptoServiceServer) FinishRegistration(context.Context, *FinishRegistrationRequest) (*FinishRegistrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinishRegistration not implemented")
}
func (UnimplementedQuartzInternalCryptoServiceServer) StartLogin(context.Context, *StartLoginRequest) (*StartLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartLogin not implemented")
}
func (UnimplementedQuartzInternalCryptoServiceServer) FinishLogin(context.Context, *FinishLoginRequest) (*FinishLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinishLogin not implemented")
}
func (UnimplementedQuartzInternalCryptoServiceServer) mustEmbedUnimplementedQuartzInternalCryptoServiceServer() {
}
func (UnimplementedQuartzInternalCryptoServiceServer) testEmbeddedByValue() {}

// UnsafeQuartzInternalCryptoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuartzInternalCryptoServiceServer will
// result in compilation errors.
type UnsafeQuartzInternalCryptoServiceServer interface {
	mustEmbedUnimplementedQuartzInternalCryptoServiceServer()
}

func RegisterQuartzInternalCryptoServiceServer(s grpc.ServiceRegistrar, srv QuartzInternalCryptoServiceServer) {
	// If the following call pancis, it indicates UnimplementedQuartzInternalCryptoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QuartzInternalCryptoService_ServiceDesc, srv)
}

func _QuartzInternalCryptoService_StartRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuartzInternalCryptoServiceServer).StartRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuartzInternalCryptoService_StartRegistration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuartzInternalCryptoServiceServer).StartRegistration(ctx, req.(*StartRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuartzInternalCryptoService_FinishRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinishRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuartzInternalCryptoServiceServer).FinishRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuartzInternalCryptoService_FinishRegistration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuartzInternalCryptoServiceServer).FinishRegistration(ctx, req.(*FinishRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuartzInternalCryptoService_StartLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuartzInternalCryptoServiceServer).StartLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuartzInternalCryptoService_StartLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuartzInternalCryptoServiceServer).StartLogin(ctx, req.(*StartLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuartzInternalCryptoService_FinishLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinishLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuartzInternalCryptoServiceServer).FinishLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuartzInternalCryptoService_FinishLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuartzInternalCryptoServiceServer).FinishLogin(ctx, req.(*FinishLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QuartzInternalCryptoService_ServiceDesc is the grpc.ServiceDesc for QuartzInternalCryptoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QuartzInternalCryptoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "quartzservice.QuartzInternalCryptoService",
	HandlerType: (*QuartzInternalCryptoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartRegistration",
			Handler:    _QuartzInternalCryptoService_StartRegistration_Handler,
		},
		{
			MethodName: "FinishRegistration",
			Handler:    _QuartzInternalCryptoService_FinishRegistration_Handler,
		},
		{
			MethodName: "StartLogin",
			Handler:    _QuartzInternalCryptoService_StartLogin_Handler,
		},
		{
			MethodName: "FinishLogin",
			Handler:    _QuartzInternalCryptoService_FinishLogin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/quartz.proto",
}
