name: PR Build Check

on:
  pull_request:
    branches:
      - master
    paths:
      - 'server/**'
      - '.github/workflows/pr.yml'

jobs:
  build-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # We don't need to login to Docker Hub because we are NOT pushing the image.
      # We just want to ensure it builds successfully.

      - name: Build quartz-server image (No Push)
        uses: docker/build-push-action@v5
        with:
          context: server
          file: server/Dockerfile.prod
          push: false
          build-args: |
            BUILD_VERSION=pr-${{ github.event.pull_request.number }}-sha-${{ github.event.pull_request.head.sha }}
          platforms: linux/amd64
          # Using GHA cache makes PR builds much faster
          cache-from: type=gha
          cache-to: type=gha,mode=max
